apiVersion: flux-framework.org/v1alpha2
kind: MetricSet
metadata:
  labels:
    app.kubernetes.io/name: metricset
    app.kubernetes.io/instance: metricset-sample
  name: metricset-sample
spec:
  # Number of pods for lammps (one launcher, the rest workers)
  pods: 4
  metrics:

   # Running more scaled lammps is our main goal
   - name: app-lammps

     # This has intel mpi on rocky linux, per suggested by Google
     image: ghcr.io/converged-computing/metric-lammps-intel-mpi:rocky

     options:
       command: mpirun --hostfile ./hostlist.txt -np 352 --map-by socket lmp -v x 64 -v y 16 -v z 16 -in in.reaxc.hns -nocite
       workdir: /opt/lammps/examples/reaxff/HNS
       soleTenancy: "true"
