apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 4
  interactive: true

  # This disables installing flux via the view
  flux:
    container:
      disable: true

  containers:
  - image: ghcr.io/converged-computing/metric-laghos:libfabric-cpu
    resources:
      limits:
        vpc.amazonaws.com/efa: 1
        memory: "340G"
        cpu: "94"

      requests:
        vpc.amazonaws.com/efa: 1
        memory: "340G" # This is actually 128
        cpu: "94"
