apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 4
  interactive: true
  flux:
    container:
      disable: true

  containers:
  - image: ghcr.io/converged-computing/metric-linpack-cpu:libfabric
    pullAlways: true
    resources:
      limits:
        vpc.amazonaws.com/efa: 1
      requests:
        vpc.amazonaws.com/efa: 1
