apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 32
  interactive: true

  # This disables installing flux via the view
  flux:
    container:
      disable: true

  # This is a list because a pod can support multiple containers
  containers:
  - image: ghcr.io/converged-computing/multi-gpu-models:flux-gpu
    workingDir: /opt/multi-gpu-programming-models/mpi
    resources:
      limits:
        cpu: 50
