apiVersion: flux-framework.org/v1alpha1
kind: MetricSet
metadata:
  labels:
    app.kubernetes.io/name: metricset
    app.kubernetes.io/instance: metricset-sample
  name: flux-sample
spec:
  # We don't have support currently for bash commands with -c quotes - hence the simple commands
  serviceName: flux-service

  # Create a minicluster of size 4
  # Node that tasks, entrypoint, etc are hard coded into the config map
  # so you need to use the same service name, etc.
  pods: 4

  # Don't set JobSet with FQDN (Flux Operator needs)
  dontSetFQDN: true

  # This is all the logic of the flux operator packaged as an application here
  application:
    image: ghcr.io/rse-ops/lammps:flux-sched-focal
    command: /bin/bash /flux_operator/wait-0.sh lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
    workingDir: /home/flux/examples/reaxff/HNS    

    volumes:
      curve:
        path: /mnt/curve/
        configMapName: flux-sample-curve-mount
        readOnly: true
        items:
          curve.cert: curve.cert
      flux-config:
        path: /etc/flux/config
        configMapName: flux-sample-flux-config
        readOnly: true
        items:
          hostfile: broker.toml
      entrypoint:
        path: /flux_operator/
        configMapName: flux-sample-entrypoint
        readOnly: true
        items:
          wait-0: wait-0.sh

  metrics:
    - name: perf-sysstat
      rate: 2
      # Useful for debugging
      # options:
      #  pids: "true"

      # Look for pids based on commands matched to index
      mapOptions:
        commands:
           # First set all to use the worker command, but give the lead broker a special command
           "all": /usr/libexec/flux/cmd/flux-broker --config /etc/flux/config -Scron.directory=/etc/flux/system/cron.d -Stbon.fanout=256 -Srundir=/run/flux -Sstatedir=/var/lib/flux -Slocal-uri=local:///run/flux/local -Slog-stderr-level=0 -Slog-stderr-mode=local
           "0": /usr/bin/python3.8 /usr/libexec/flux/cmd/flux-submit.py -n 2 --quiet --watch lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite

