apiVersion: flux-framework.org/v1alpha2
kind: MetricSet
metadata:
  labels:
    app.kubernetes.io/name: metricset
    app.kubernetes.io/instance: metricset-sample
  name: hpctoolkit-0
spec:
  pods: 1
  serviceName: oras
  pod:
    annotations:
     oras.converged-computing.github.io/oras-cache: oras
     oras.converged-computing.github.io/output-uri: metric/hpctoolkit-test:[[TAG]]
     oras.converged-computing.github.io/output-path: /opt/lammps/examples/reaxff/HNS
     oras.converged-computing.github.io/unpack: "false"
     oras.converged-computing.github.io/debug: "true"
  metrics:
   - name: app-lammps
     image: ghcr.io/converged-computing/metric-lammps-intel-mpi:rocky
     options:
       command: lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
       workdir: /opt/lammps/examples/reaxff/HNS
     addons:
       - name: perf-hpctoolkit
         options:
           mount: /opt/mnt
           events:  "-e REALTIME@100"
           image: ghcr.io/converged-computing/metric-hpctoolkit-view:rocky            
           prefix: /opt/intel/mpi/2021.8.0/bin/mpirun --hostfile ./hostlist.txt -np 4 --map-by socket
           workdir: /opt/lammps/examples/reaxff/HNS
           containerTarget: launcher
