apiVersion: flux-framework.org/v1alpha2
kind: MetricSet
metadata:
  labels:
    app.kubernetes.io/name: metricset
    app.kubernetes.io/instance: metricset-sample
  name: metricset-sample
spec:
  pods: 1
  serviceName: oras
  pod:
    annotations:
     oras.converged-computing.github.io/oras-cache: oras
     oras.converged-computing.github.io/output-uri: metric/hwloc:[[TAG]]
     oras.converged-computing.github.io/output-path: /tmp/analysis
     oras.converged-computing.github.io/debug: "true"

  metrics:
    - name: sys-hwloc      
      # These are the default and do not need to be provided
      options:
      listOptions:
        command:
          - mkdir -p /tmp/analysis
          - lstopo /tmp/analysis/architecture.png
          - hwloc-ls /tmp/analysis/machine.xml
