apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-gcs-pvc
spec:
  storageClassName: csi-gcs
  # Note this will just work with one pod
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi