apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-07T23:53:01Z"
  name: flux-service
  namespace: default
  ownerReferences:
  - apiVersion: flux-framework.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: MiniCluster
    name: flux-sample
    uid: ac8e9bf2-24d4-4a0e-bc78-f26513b8e355
  resourceVersion: "5780"
  uid: 21f78de5-b10a-4e84-a1c3-e29170368ec4
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    job-name: flux-sample
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
