apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2023-08-07T23:53:01Z"
  generation: 1
  labels:
    app.kubernetes.io/name: flux-sample
    controller-uid: 0d848340-91a3-46cf-99de-b748d23d953f
    hpa-selector: flux-sample
    job-name: flux-sample
    namespace: default
  name: flux-sample
  namespace: default
  ownerReferences:
  - apiVersion: flux-framework.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: MiniCluster
    name: flux-sample
    uid: ac8e9bf2-24d4-4a0e-bc78-f26513b8e355
  resourceVersion: "5799"
  uid: 0d848340-91a3-46cf-99de-b748d23d953f
spec:
  activeDeadlineSeconds: 31500000
  backoffLimit: 100
  completionMode: Indexed
  completions: 4
  parallelism: 4
  selector:
    matchLabels:
      controller-uid: 0d848340-91a3-46cf-99de-b748d23d953f
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: flux-sample
        controller-uid: 0d848340-91a3-46cf-99de-b748d23d953f
        hpa-selector: flux-sample
        job-name: flux-sample
        namespace: default
      name: flux-sample
      namespace: default
    spec:
      containers:
      - command:
        - /bin/bash
        - /flux_operator/wait-0.sh
        - lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
        image: ghcr.io/rse-ops/lammps:flux-sched-focal
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        name: flux-sample
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /mnt/curve/
          name: flux-sample-curve-mount
          readOnly: true
        - mountPath: /etc/flux/config
          name: flux-sample-flux-config
          readOnly: true
        - mountPath: /flux_operator/
          name: flux-sample-entrypoint
          readOnly: true
        workingDir: /home/flux/examples/reaxff/HNS
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      setHostnameAsFQDN: false
      shareProcessNamespace: false
      subdomain: flux-service
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: hostfile
            path: broker.toml
          name: flux-sample-flux-config
        name: flux-sample-flux-config
      - configMap:
          defaultMode: 420
          items:
          - key: wait-0
            mode: 511
            path: wait-0.sh
          name: flux-sample-entrypoint
        name: flux-sample-entrypoint
      - configMap:
          defaultMode: 420
          name: flux-sample-curve-mount
        name: flux-sample-curve-mount
status:
  active: 4
  ready: 0
  startTime: "2023-08-07T23:53:01Z"
