apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 2
  interactive: true
  flux:
    container:
      disable: true
  containers:
  - image: ghcr.io/converged-computing/metric-amg2023:vtune
    pullAlways: true
    commands:
       pre: |
        . /etc/profile.d/z10_spack_environment.sh
        echo "Regenerated resources"
        flux R encode --hosts=${hosts} --local > ${viewroot}/etc/flux/system/R
        cat ${viewroot}/etc/flux/system/R
    resources:
      limits:
        vpc.amazonaws.com/efa: 1
      requests:
        vpc.amazonaws.com/efa: 1
    securityContext:
      privileged: true
