apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 1
  interactive: true

  # This disables installing flux via the view
  flux:
    container:
      disable: true

  containers:
  - image: ghcr.io/converged-computing/metric-nek5000:vtune
    pullAlways: true
    resources:
      limits:
        vpc.amazonaws.com/efa: 1
      requests:
        vpc.amazonaws.com/efa: 1
    securityContext:
      privileged: true
