# hpc6a only in this region
Region: us-east-2
Image:
  Os: ubuntu2004
HeadNode:
  InstanceType: hpc6a.48xlarge
  Networking:
    SubnetId: subnet-0d174d28f9f2e9bde
  Ssh:
    KeyName: tahcos-cat
  LocalStorage:
    RootVolume:
      Size: 50
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
#  CustomActions:
#    OnNodeConfigured:
      # I made this publicly accessible with ACL after upload to the interface and then via the UI
#      Script: https://performance-study-2024.s3.us-east-2.amazonaws.com/parallel-cluster-performance-study-install.sh

Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
#    CustomActions:
#      OnNodeConfigured:
#        Script: https://performance-study-2024.s3.us-east-2.amazonaws.com/parallel-cluster-performance-study-install.sh
    ComputeResources:
    - Name: hpc6a48xlarge
      Instances:
      - InstanceType: hpc6a.48xlarge
      MinCount: 2
      MaxCount: 2    
      Efa:
        Enabled: true
    ComputeSettings:
      LocalStorage:
        RootVolume:
          Size: 50
    Networking:
      SubnetIds:
      - subnet-062e29f54aab2ced2
      PlacementGroup:
        Enabled: true
        Id: performance-study

# When I enable this, some of the nodes will fail provisioning and roll back
#    CustomActions:
#        OnNodeConfigured:
#          Script: >-
#                        https://gist.githubusercontent.com/vsoch/445b720c4a6c49a1bc1535acfec79cea/raw/edf45fbb8137c0c0b95726a82fc5540b1b399c88/install.sh
# I don't think we actually need this either...
#SharedStorage:
#- MountDir: /shared      
#  Name: ebs
#  StorageType: Ebs
#  EbsSettings:
    # Might be better to use gp3 for experiments?
#    VolumeType: gp2
#    Size: 100

# I'm not starting with this - I don't think we need it
#    - MountDir: /scratch 
#      Name: fsx
#      StorageType: FsxLustre
#      FsxLustreSettings:
#        StorageCapacity: 1200
#        DeploymentType: SCRATCH_2
#        ImportPath: s3:<PATH-TO-IMPORT-FILES>
