apiVersion: flux-framework.org/v1alpha2
kind: MetricSet
metadata:
  labels:
    app.kubernetes.io/name: metricset
    app.kubernetes.io/instance: metricset-sample
  name: metricset-sample
spec:
  pods: 64
  metrics:
   - name: network-osu-benchmark
     # Custom list of commands to run
     # See https://converged-computing.github.io/metrics-operator/getting_started/metrics.html#network-osu-benchmark
     listOptions:
       commands:
        - osu_allreduce
        - osu_hello
     options:
       # Wrap each one in time
       timed: "true"
       flags: "-np 64 -map-by ppr:1:node -rank-by core"
       sleep: 10
