apiVersion: flux-framework.org/v1alpha2
kind: MetricSet
metadata:
  labels:
    app.kubernetes.io/name: metricset
    app.kubernetes.io/instance: metricset-sample
  name: metricset-sample
spec:
  pods: 8
  metrics:
   - name: network-osu-benchmark
     listOptions:
       commands:
        - osu_hello
        - osu_allreduce
     options:
       timed: "true"
       flags: "-np 8 -map-by ppr:1:node -rank-by core"
       sleep: 10
