apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  # 1792
  size: 32
  interactive: true
  flux:
    container:
      disable: true
  containers:
  - image: ghcr.io/converged-computing/metric-amg2023:spack-slim-cpu
    commands:
      pre: |
        . /etc/profile.d/z10_spack_environment.sh
        echo "Regenerated resources"
        flux R encode --hosts=${hosts} --local > ${viewroot}/etc/flux/system/R
        cat ${viewroot}/etc/flux/system/R        
    resources:
      limits:
        cpu: 50
