apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 16
  interactive: true
  flux:
    container:
      disable: true

  containers:
  - image: ghcr.io/converged-computing/metric-kripke-cpu
