apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 32
  interactive: true

  # This disables installing flux via the view
  flux:
    container:
      disable: true

  containers:
  - image: ghcr.io/converged-computing/metric-quicksilver-cpu
